### ISSUE TITLE
Imprint page 404

### ISSUE THREAD

**Issue by orc-hfg** [victor-fancelli-capdevila/abc_dl#5]
The imprint-page does not exist:

![Bildschirm­foto 2022-10-31 um 17 05 14](https://user-images.githubusercontent.com/98032127/199055733-1e74f530-fe19-4711-a4cb-7c1c03b03299.jpg)

![Bildschirm­foto 2022-10-31 um 17 04 48](https://user-images.githubusercontent.com/98032127/199055703-269da3f7-cb90-4686-a690-65f4ee0228b8.jpg)

**Comment by victor-fancelli-capdevila** [comment]
Dear orc-hfg,

thank you very much for reporting an issue. I created the link, but I was waiting until having the page to link to: that explains the "page not found" of your second image. Now everything should work fine (or less nonfunctional). Thank you also for the patience... sometimes it takes longer as expected...

For everyone reading this, we can learn two things:

## Issue report
That's basically how an **issue report** works. Someone (in this case orc-hfg, but it could be you) reports that there is an issue (in this case: there is no imprint page). In order to do that, it's important to be clear on how to reproduce the problem, or at least communicate what the problem is. Orc-hfg used two pictures, and we could quickly understand what the problem was. A good approach is also to think in three questions: 
1. **what did you do?** (first image, clicking on imprint), 
2. **what did you expect to happen?** (in this case obvious, to be linked to the imprint page after clicking the link) and 
3. **what did actually happen?** (getting a 404 error page). 

It is possible that maintainers or developers contact you to get more information about the problem: yes, suddenly you become a world expert or at least the most reliable source to this problem!

## Imprint pages
Imprint pages is the part of a publication that connects this document with an authorship and ownership, which implies legal responsibilities. It's the equivalent to the page (normally at the beginning, sometimes at the end) in which you will find all the editorial information, ISBN, etc. in a book: this is crucial if you decide to take any legal action. In Germany (and in many other countries), websites are obligated to declare who is responsible for them, according to the [_Telemediengesetz_](https://www.gesetze-im-internet.de/tmg/__5.html). 

In the first part of [our imprint](https://victor-fancelli-capdevila.github.io/abc_dl/imprint/), you will find information about how to contact me, as I am the ultimate responsible for the website. Then, we attached some disclaimers to protect us against possible complaints. It's a quite standard procedure, and I just copy search for a template in internet (the first result happens to be from [JuraForum](https://www.juraforum.de/), in German). I have no idea how good or bad they are, so I compared with the Imprint of other websites I consider reliable and after checking that nothing was miss and that everything there makes sense, I create the imprint page. I'm not an expert on this topic (and hence I cannot recommend you any services), but your personal data is mandatory, and the disclaimers seems a standard protection. For the English version, I translated and added the note at the beginning, indicating that the "real" version is the [German](https://victor-fancelli-capdevila.github.io/abc_dl/de/imprint/): this makes sense, because everything will be processed by the German legal system. 

If you're working in a website, you should clarify this point as soon as possible: Here you are declaring who is the ultimate responsible person or group of every information on the web. In the university context, this person could be the rector, or the director in cultural institutions. I decided to take the responsibility of the "The abc of digital literacy" website, because I understand as a project or materials which are part of the course I was teaching. From my point of view, the responsible should control (and proof) all the published information. As I am already "proofreading" all the changes of the website, I have no problem on getting this responsibility. Of course, we may change this (and the imprint) if we need it.
